services:
  postgres-mm:
    image: docker.arvancloud.ir/postgres:16-alpine
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - ${POSTGRES_DATA_PATH:-./volumes/db}:/var/lib/postgresql/data
    environment:
      - TZ=${TZ:-Asia/Tehran}
      - POSTGRES_USER=${POSTGRES_USER:-mmuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mmuser_password}
      - POSTGRES_DB=${POSTGRES_DB:-mattermost}
    networks:
      mattermost-net:

  mattermost:
    depends_on:
      - postgres-mm
    image: docker.arvancloud.ir/mattermost/${MATTERMOST_IMAGE:-mattermost-team-edition}:${MATTERMOST_IMAGE_TAG:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '127.0.0.1:8065:8065'
      - '${CALLS_PORT:-8445}:8445/udp'
      - '${CALLS_PORT:-8445}:8445/tcp'
    volumes:
      - ${MATTERMOST_CONFIG_PATH:-./volumes/app/mattermost/config}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH:-./volumes/app/mattermost/data}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH:-./volumes/app/mattermost/logs}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH:-./volumes/app/mattermost/plugins}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH:-./volumes/app/mattermost/client/plugins}:/mattermost/client/plugins:rw
      - ${MATTERMOST_BLEVE_INDEXES_PATH:-./volumes/app/mattermost/bleve-indexes}:/mattermost/bleve-indexes:rw
    environment:
      - TZ=${TZ:-Asia/Tehran}
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://${POSTGRES_USER:-mmuser}:${POSTGRES_PASSWORD:-mmuser_password}@postgres-mm:5432/${POSTGRES_DB:-mattermost}?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - MM_SERVICESETTINGS_SITEURL=${MM_SERVICESETTINGS_SITEURL}
      - MM_SERVICESETTINGS_LISTENADDRESS=:8065
      - MM_PLUGINSETTINGS_ENABLEUPLOADS=true
    networks:
      mattermost-net:

networks:
  mattermost-net:
